# Generated by Django 4.1.1 on 2022-10-13 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("client", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contract", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_status",
                    models.CharField(
                        choices=[("ongoing", "ONGOING"), ("ended", "ENDED")],
                        max_length=10,
                    ),
                ),
                ("attendees", models.PositiveIntegerField()),
                ("event_date", models.DateTimeField()),
                ("notes", models.TextField()),
                ("date_created", models.DateTimeField(editable=False)),
                ("date_updated", models.DateTimeField(editable=False)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_client",
                        to="client.client",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_contract",
                        to="contract.contract",
                    ),
                ),
                (
                    "support_contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_support_contact",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
