# Generated by Django 4.1 on 2022-09-01 12:46

from django.db import migrations

def create_groups(apps, schema_migration):
    User = apps.get_model('authentication', 'User')
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    add_user = Permission.objects.get(codename='add_user')
    change_user = Permission.objects.get(codename='change_user')
    delete_user = Permission.objects.get(codename='delete_user')
    view_user = Permission.objects.get(codename='view_user')

    view_group = Permission.objects.get(codename='view_group')

    add_client = Permission.objects.get(codename='add_client')
    change_client = Permission.objects.get(codename='change_client')
    view_client = Permission.objects.get(codename='view_client')
    
    add_contract = Permission.objects.get(codename='add_contract')
    change_contract = Permission.objects.get(codename='change_contract')
    view_contract = Permission.objects.get(codename='view_contract')

    add_event = Permission.objects.get(codename='add_event')
    change_event = Permission.objects.get(codename='change_event')
    view_event = Permission.objects.get(codename='view_event')

    sales_permissions = [
        add_client,
        change_client,
        view_client,
        change_contract,
        view_contract,
        add_event,
     ]

    support_permissions = [
        change_event,
        view_event,
        view_client,
    ]

    management_permissions = [
        add_user,
        change_user,
        delete_user,
        view_user,
        change_client,
        view_client,
        change_contract,
        view_contract,
        change_event,
        view_event,
        view_group,
    ]
    
    sales_team = Group(name='sales_permissions')
    sales_team.save()
    sales_team.permissions.set(sales_permissions)

    support_team = Group(name='support_team')
    support_team.save()
    support_team.permissions.set(support_permissions)

    management_team = Group(name='management_team')
    management_team.save()
    management_team.permissions.set(management_permissions)
    
    for user in User.objects.all():
        if user.role == 'SALES':
            sales_team.user_set.add(user)
        if user.role == 'SUPPORT':
            support_team.user_set.add(user)
        if user.role == 'MANAGEMENT':
            management_team.user_set.add(user)

class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_groups)
    ]
