# Generated by Django 4.1 on 2022-08-31 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creation_date", models.DateTimeField(editable=False)),
                ("last_modified", models.DateTimeField(editable=False)),
                (
                    "event_status",
                    models.CharField(
                        choices=[("ongoing", "ONGOING"), ("ended", "ENDED")],
                        max_length=10,
                    ),
                ),
                ("attendees", models.PositiveIntegerField()),
                ("event_date", models.DateTimeField()),
                ("notes", models.TextField()),
                (
                    "client_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_client",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "support_contact_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_support_contact",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creation_date", models.DateTimeField(editable=False)),
                ("last_modified", models.DateTimeField(editable=False)),
                ("status", models.BooleanField()),
                ("amount", models.FloatField()),
                ("payment_due", models.DateTimeField(null=True)),
                (
                    "client_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contract_client",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sales_contact_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contract_sales_contact",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creation_date", models.DateTimeField(editable=False)),
                ("last_modified", models.DateTimeField(editable=False)),
                ("firstname", models.CharField(max_length=25)),
                ("lastname", models.CharField(max_length=25)),
                ("email", models.EmailField(max_length=100)),
                ("phone", models.CharField(max_length=20)),
                ("mobile", models.CharField(max_length=20)),
                ("company_name", models.CharField(max_length=250)),
                (
                    "sales_contact_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_sales_contact",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
